### ISSUE TITLE
[CMake] The compilation flags and configuration is not applied to the "main" project when adding this library via add_subdirectory()

### ISSUE THREAD

**Issue by Ybalrid** [ddovod/jet-live#31] opened 2019-04-14 19:51 UTC
**update**: The actual problem here was that the complilation and link flags that should be changed by the CMakeList.txt flag inside this reposiotry were not applied to the code built by the project that included it via `add_subdirectory()`

Hi, I'm currently trying to implement jet-live inside a little SDL/OpenGL framework. I'm using a bunch of libraries, some of them are header only. One compilation unit ` #define`  a token that makes the header spits out the whole implementation there.

The compiled symbols from that library ends up inside the executable of the program.

When I attempt to modify one of the files of this project following the README, it is compiled without any error into a .so file.

When jet-live tries to load that .so file, I get an error like this : 

all of this is on Linux x86_64, using GCC 8.2.0, CMake 3.14.2 and ninja 1.9.2.

```
jet-live  Ready
jet-live  Compiling: application.cpp
jet-live  Success: application.cpp
jet-live  Trying to reload code...
jet-live  Linking...
jet-live  Link command:
/usr/bin/c++ -fPIC -shared -g -Wl,-Ttext-segment,0x406ad000 -Wl,-z,max-page-size=0x1000 -Wl,-export-dynamic -Wl,-soname,lib_reload1.so -o lib_reload1.so "/home/ybalrid/Programming/opengl_sdl_base/build_debug_ninja/CMakeFiles/test_project_exe.dir/src/application.cpp.o" 
jet-live  Linked successfully
jet-live  Opening /home/ybalrid/Programming/opengl_sdl_base/build_debug_ninja/lib_reload1.so...
jet-live  Cannot open library /home/ybalrid/Programming/opengl_sdl_base/build_debug_ninja/lib_reload1.so
/home/ybalrid/Programming/opengl_sdl_base/build_debug_ninja/lib_reload1.so: undefined symbol: _ZN8tinygltf14WriteWholeFileEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS5_RKSt6vectorIhSaIhEEPv
```

Here are some info about that symbol found with objdump:

```
ybalrid:build_debug_ninja/ (jet-live✗) $ objdump -x lib_reload1.so | grep _ZN8tinygltf14WriteWholeFileEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS5_RKSt6vectorIhSaIhEEPv                                    
0000000000000000         *UND*  0000000000000000              _ZN8tinygltf14WriteWholeFileEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS5_RKSt6vectorIhSaIhEEPv
ybalrid:build_debug_ninja/ (jet-live✗) $ objdump -x test_project_exe | grep _ZN8tinygltf14WriteWholeFileEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS5_RKSt6vectorIhSaIhEEPv                                  
00000000000af5fd g     F .text  0000000000000297              _ZN8tinygltf14WriteWholeFileEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS5_RKSt6vectorIhSaIhEEPv
ybalrid:build_debug_ninja/ (jet-live✗) $    
```

I do not understand how this symbol can be unresolved at this point. The executable image running has this symbol defined. I don't know enough about the dynamic loader on Linux to see anything obviously wrong with what's going on.

I've been digging for an hour or so, but I cannot find the cause of my problem. :sweat_smile:

**Comment by ddovod** [comment] 2019-04-14 21:03
Hi. Glad to hear you're trying it = )
Could you tell please, do you use CMakeLists.txt from the jet-live library to include it in your application? Asking because CMakeLists.txt contains crucial compiler and linker flags, especially `-export-dynamic` on linux, are you sure your application is linked with this flag? You can check it in `link.txt` somewhere in `build/CMakeFiles` directory.
Also do you use the latest version of jet-live from master? I'm fixing bugs from time to time so probably it is already fixed.
Also, it would be really great if I can reproduce it on my side, so probably you can share the project somehow?

**Comment by Ybalrid** [comment] 2019-04-14 21:16
okay, so:
1) I'm using the CMakeLists.txt file directly by using ` add_subdirectory` as presented in your README, however, it seems that some of the settings it changes aren't applied correctly. I'm trying to diagnose this...

2) When setting -export-dynamic (I copied that line from your CMake to the root one) I get a segfault, I'm trying to understand it's origin right now. What I can tell is that indeed, this was the missing thing that prevented dlopen to successfully work. That segfault is from a std::string constructor as far as I can tell, but I don't really know it's origin. It occurs after the linking, after the loading of the library. stack-trace at the point of crash is useless so I'm stepping inside the debugger to try to assess what's going on.

3) I'm using the master branch, commit 14b909b00b98399d7e046cd8b7500a3fdfe0a0b1

I'm going to check the whole cmake thing before going forward, maybe it's just that.

If I am really desperate, I'll try to share that project with you, but I need to do some cleanup and push that test branch, I'm not ready to do that just yet. :joy:

**Comment by ddovod** [comment] 2019-04-14 21:24
Sure, no problem, just let me know. It really looks like some cmake misconfiguration. Also, since you're using GCC, please pay attention to the `-falign-functions=16` flag, you can get crashes if this flag is not set globally for all cpp files.
About c++17, it doesn't matter at all, I'm working with this lib every day under linux in c++17 project.

**Comment by Ybalrid** [comment] 2019-04-14 21:32
Yes, there's something strange about what CMake is doing I think.

For example, if I don't put manually the ` set(CMAKE_EXPORT_COMPILE_COMMANDS ON) ` flag in my top-level cmake file, the compile_commands.json generated only list jet-live's CUs. Not mines.

**Comment by ddovod** [comment] 2019-04-14 21:39
Oh, probably this is the case. I'm not a cmake-guru, but could you please try to copy a part of CMakeLists.txt starting from `set(CMAKE_EXPORT_COMPILE_COMMANDS ON)` and to `########## lib_subhook` into your root CMakeLists.txt file and check if it fix you issue?

**Comment by Ybalrid** [comment] 2019-04-14 21:40
here's what I do in my CMake file 

```cmake
IF (UNIX)
        SET(JET_LIVE_BUILD_EXAMPLE OFF)
        ADD_SUBDIRECTORY(third_party/jet-live)
        MESSAGE("we are using jet-live")
        ADD_DEFINITIONS(-DUSING_JETLIVE) #add jet-live integration in my source code
ENDIF()

# here are definitions of things to be built by my project, this defined a target called "test_project_exe"

TARGET_LINK_LIBRARIES(test_project_exe PUBLIC jet-live)
```

I'm copying the modified flags to my CMake file and we'll see if it works.

**Comment by Ybalrid** [comment] 2019-04-14 21:43
It appears to be working (need to test it a bit more, it's complaining about realocation distances right now)

CMake define things at the directory scope by default... I'm going to see if I can improve your cmake file so that we are sure these settings are applied globally.

**Comment by Ybalrid** [comment] 2019-04-14 21:48
okay, this was the problem. It works. I'm changing the issue title to reflect the situation ;-)

**Comment by ddovod** [comment] 2019-04-14 21:54
Awesome, thank you for investigation! I'll think about how to fix it.
Also if you have some ideas, don't hesitate to share = )

**Comment by Ybalrid** [comment] 2019-04-14 22:09
I'm probably going to try to make the CMakeList file a bit better for that usage, because that's the easiest way to integrate that library to a project.

I will make a pull request if I "fix" this :wink:

In the mean time, you could add to the ReadMe the spinet of CMake configuration that is required for everything to work (the lines you mentioned in your last message here), and telling the user that if it does't work, they try to add this before the target definitions in their own CMakeLists.txt file.

Ideally it should "just works", but when it fails... :man_shrugging:

**Comment by ddovod** [comment] 2019-04-15 11:19
So I've made a change in the least intrusive way I found. Could you please try this fix? You should remove your main cmake file modifications and just include `cmake/jet_live_setup.cmake` file into your main CMakeLists.txt, this is a branch (see updated readme)
https://github.com/ddovod/jet-live/tree/fix_cmake_config

**Comment by Ybalrid** [comment] 2019-04-15 16:23
I'm going to see, but really I think the only thing needed is the ` PARENT_SCOPE` option in all the thing you ` set()` that should influence the user's CMakeLists

**Comment by Ybalrid** [comment] 2019-04-15 16:32
I'm going to submit a pull request with a simpler fix that doesn't require the user to `include()` anything.

**Comment by Ybalrid** [comment] 2019-04-15 16:34
^^^
Please consider the linked PR #34

**Comment by Ybalrid** [comment] 2019-04-15 18:50
The changes in #32 are working fine on my side

**Comment by ddovod** [comment] 2019-04-15 21:03
Thank you again! Closing this for now

**Closed by ddovod** 2019-04-15 21:03 UTC
